task added for all pages
edly-io/loadtest-scripts pull request #1
Opened 2021-07-30 04:50 UTC by fayyazahmed66

I have added the rest of the WordPress pages into the script. 
Here is the Ticket link: https://edlyio.atlassian.net/browse/EDLY-3330

2021-07-30 05:57 UTC, ziafazal commented
@fayyazahmed66 pyc file should not be commited.

2021-07-30 07:39 UTC, burhandodhy reviewed
@fayyazahmed66 please add task that open course detail page.

2021-08-03 10:57 UTC, burhandodhy requested changes

2021-08-03 10:57 UTC, burhandodhy commented on simple_test.py
>          self.client.get("/")
Kindly add one line space after function

2021-08-03 12:35 UTC, burhandodhy approved these changes

2021-08-06 11:46 UTC, merged